kind: Template
metadata:
  name: b61ad08d-c419-4865-90e3-957e7e99ec64
  description: Yaml of action history Group Service
spec:
  parameters:
    - required:
        - name
        - argocd
        - test_link
      errorMessage:
        required:
          name: Name is required
          argocd: ArgoCD is required
          test_link: Test Link is required
      properties:
        name:
          title: Name
          type: string
          description: ''
          ui:order: 1
          default: Create Gr service Quandev
        description:
          title: Description
          type: string
          description: Description
          ui:order: 2
          default: Create Gr service Quandev
          minLength: 1
        argocd:
          title: ArgoCD
          type: string
          description: Group Service
          ui:order: 3
          default: http://localhost:3000/self-service-action
          format: uri
        test_link:
          title: Test Link
          type: string
          description: Test Link
          ui:order: 4
          default: http://localhost:3000/self-service-action
          format: uri
      type: object
      title: b61ad08d-c419-4865-90e3-957e7e99ec64
  type: Service
  title: b61ad08d-c419-4865-90e3-957e7e99ec64
  steps:
    - id: backstage_request_to_webhook
      name: backstage request to webhook
      action: http:backstage:request
      input:
        method: POST
        path: /orchestrator-be/forward-request
        body:
          reqBody: ${{parameters}}
          forwardTo:
            url: http://localhost:5000/update-user
            type: 2
            method: POST
    - id: register_catalog_callback
      name: register catalog callback
      action: http:backstage:request
      input:
        method: POST
        path: /orchestrator-be/catalogs
        body:
          reqBody: ${{parameters}}
          response: '{{ steps.backstage_request_to_webhook.output.body }}'
  lifecycle: production
apiVersion: scaffolder.backstage.io/v1beta3
