kind: Template
metadata:
  name: 9993fd65-c7c1-4a70-a486-4f0b3b5bf746
  description: Yaml of action history CreateDatabase
spec:
  parameters:
    - required:
        - name
        - host
      errorMessage:
        required:
          name: Name is required
          host: Host is required
      properties:
        name:
          title: Name
          type: string
          description: ''
          ui:order: 1
          default: vds-db
        host:
          title: Host
          type: string
          description: ''
          ui:order: 2
          default: http://localhost:3000
          format: uri
      type: object
      title: 9993fd65-c7c1-4a70-a486-4f0b3b5bf746
  type: Service
  steps:
    - id: backstage_request_to_webhook
      name: backstage request to webhook
      action: http:backstage:request
      input:
        method: POST
        path: /orchestrator-be/forward-request
        headers:
          content-type: application/json
        body: '{"parameters":"${{ parameters }}","forward":{"url":"http://localhost:3000/update-user","type":2,"method":"POST"}}'
    - id: register_catalog_callback
      name: register catalog callback
      action: http:backstage:request
      input:
        method: POST
        path: /orchestrator-be/catalogs
        headers:
          content-type: application/json
        body:
          parameters: ${{ parameters }}
          response: '{{ steps.backstage_request_to_webhook.output.body }}'
  lifecycle: production
apiVersion: scaffolder.backstage.io/v1beta3
